### ISSUE TITLE
新版本的easywebpack-cli在easy clean all的时候报错

### ISSUE THREAD

**Issue by zhouyuping09** [hubcarl/easywebpack-cli#9]
系统： win 10
报错图片如下：
D:\project\aaa>npm run clean

> kikuu-msite@1.0.0 clean D:\project\aaa
> easywebpack clean all

remove [ C:\Users\admin\AppData\Local\Temp\easywebpack\aaa ] success
fs.js:904
  return binding.readdir(pathModule._makeLong(path), options.encoding);
                 ^

Error: ENOTDIR: not a directory, scandir 'D:\project\aaa\config\manifest.json'
    at Object.fs.readdirSync (fs.js:904:18)
    at Object.exports.deleteFile.filepath [as deleteFile] (D:\project\aaa\node_modules\_easywebpack-cli@3.11.2@easywebpack-cli\
lib\tool.js:30:22)
    at dirs.forEach.dir (D:\project\aaa\node_modules\_easywebpack-cli@3.11.2@easywebpack-cli\lib\tool.js:14:15)
    at Array.forEach (<anonymous>)
    at Object.exports.rm.filepath [as rm] (D:\project\aaa\node_modules\_easywebpack-cli@3.11.2@easywebpack-cli\lib\tool.js:11:8
)
    at Object.clearManifest (D:\project\aaa\node_modules\_easywebpack-cli@3.11.2@easywebpack-cli\lib\utils.js:151:12)
    at Command.program.command.description.action.dir (D:\project\aaa\node_modules\_easywebpack-cli@3.11.2@easywebpack-cli\bin\
cli.js:180:13)
    at Command.listener (D:\project\aaa\node_modules\_commander@2.17.1@commander\index.js:315:8)
    at emitTwo (events.js:126:13)
    at Command.emit (events.js:214:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! aaa@1.0.0 clean: `easywebpack clean all`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the aaa@1.0.0 clean script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by hubcarl** [comment]
目录不存在，已修复
